# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 13:49
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import worldcup_standings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_type', models.CharField(choices=[(b'Yellow', b'Yellow'), (b'Red', b'Red')], default=b'Yellow', max_length=15)),
                ('time', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(140), django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(140), django.core.validators.MinValueValidator(0)])),
                ('is_penalty', models.BooleanField(default=False)),
                ('allowed', models.CharField(choices=[(b'Allowed', b'Allowed'), (b'DisAllowed', b'DisAllowed')], default=b'Allowed', max_length=15)),
                ('owngoal', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score1', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('score2', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('penality1', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('penality2', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('venue', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[(b'LIVE', b'LIVE'), (b'HALF TIME', b'HALF TIME'), (b'FULL TIME', b'FULL TIME')], default=None, max_length=20)),
                ('result', models.CharField(choices=[(b'WON', b'WON'), (b'LOST', b'LOST'), (b'DRAW', b'DRAW')], default=b' ', max_length=100)),
                ('gametime', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('position', models.CharField(max_length=100, null=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('flag', models.ImageField(null=True, upload_to=worldcup_standings.models.change_file_name)),
                ('group', models.CharField(max_length=2)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='players',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldcup_standings.Teams'),
        ),
        migrations.AddField(
            model_name='matches',
            name='captain_team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Captain_team1', to='worldcup_standings.Players'),
        ),
        migrations.AddField(
            model_name='matches',
            name='captain_team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Captain_team2', to='worldcup_standings.Players'),
        ),
        migrations.AddField(
            model_name='matches',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='worldcup_standings.Teams'),
        ),
        migrations.AddField(
            model_name='matches',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='worldcup_standings.Teams'),
        ),
        migrations.AddField(
            model_name='goals',
            name='assist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assist', to='worldcup_standings.Players'),
        ),
        migrations.AddField(
            model_name='goals',
            name='awarded_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='worldcup_standings.Teams'),
        ),
        migrations.AddField(
            model_name='goals',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='worldcup_standings.Matches'),
        ),
        migrations.AddField(
            model_name='goals',
            name='scorer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorer', to='worldcup_standings.Players'),
        ),
        migrations.AddField(
            model_name='cards',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='worldcup_standings.Matches'),
        ),
        migrations.AddField(
            model_name='cards',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='worldcup_standings.Players'),
        ),
    ]
